---
# This playbook does a rolling update for all webservers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#

- hosts: webservers
  serial: 1

  # These are the tasks to run before applying updates:
  tasks:

  - name: disable nagios alerts for this host webserver service
    nagios: 'action=disable_alerts host={{ inventory_hostname }} services=webserver'
    delegate_to: "{{ item }}"
    with_items: "{{ groups.monitoring }}"

  - name: disable the server in haproxy
    haproxy: 'state=disabled backend=myloadbalancer host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
    delegate_to: "{{ item }}"
    with_items: "{{ groups.lbservers }}"

  - name: pause to let us review the status after remiving the first host from nagios and lb
    pause: 
      seconds: 10
 
  # The next task applies updates
  - name: Update the system packages
    yum: 
      name: "{{item}}"
      state: latest
    with_items: "{{pkg_list}}"

  # These tasks run after the roles:
  - name: wait for webserver to come up
    wait_for: 'host={{ ansible_ssh_host }} port=80 state=started timeout=80'

  - name: enable the server in haproxy
    haproxy: 'state=enabled backend=myloadbalancer host={{ inventory_hostname }} socket=/var/lib/haproxy/stats'
    delegate_to: "{{ item }}"
    with_items: "{{ groups.lbservers }}"

  - name: re-enable nagios alerts
    nagios: 'action=enable_alerts host={{ inventory_hostname }} services=webserver'
    delegate_to: "{{ item }}"
    with_items: "{{ groups.monitoring }}"
