---
# This playbook does a rolling update for all webservers serially (one at a time).
# Change the value of serial: to adjust the number of server to be updated.
#

- hosts: "{{ targethost }}"
  serial: 1

  tasks:

  # The next task applies updates
  - name: Update the system packages
    yum: 
      name: "{{ item }}"
      state: latest
    with_items: "{{ pkg_list }}"
    notify: 
      - reboot if needed
      - Wait for server to restart

  handlers:
  
  - name: reboot if needed
    command: /usr/bin/systemd-run --on-active=4 /usr/bin/systemctl reboot
    async: 0
    poll: 0
    ignore_errors: true
    become: true

  - name: Wait for server to restart
    wait_for:
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      port: 22
      delay: 10
    connection: local
    become: false
